# -*- coding: utf-8 -*-
"""llama_loratrained_instructiontuning_MDLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kM8BT7buy4DtbkSSqH1V-VGtUa-BrLVn

Install required Python packages for training, logging, and visualization.
"""

!pip install safetensors numpy torch torchvision torchaudio transformers accelerate peft datasets tokenizers wandb gradio ipywidgets matplotlib torchinfo -q

pip install torchao --upgrade -q

from google.colab import output
output.enable_custom_widget_manager()

"""Core imports and global settings for training (transformers, accelerate, datasets, numpy/matplotlib), and define the fixed sequence length of 256.

"""

# 2. Imports and Setup
import gc
import torch
import numpy as np
import matplotlib.pyplot as plt
from accelerate import Accelerator
import wandb
import torch

from datasets import load_dataset, DatasetDict
from transformers import (
    TrainingArguments,
    Trainer,
    TrainerCallback,
    TrainerState,
    TrainerControl,
)
from dataclasses import dataclass

input_size = 1024

"""Initialize Accelerate and select the active device (CPU/GPU).

"""

# Initialize Accelerator once; fallback to torch device if needed
accelerator = Accelerator()

# Move model and data to the right device (CPU or GPU)
device = accelerator.device if accelerator is not None else torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

"""Load the Llama 3.2-1B-Instruct tokenizer

"""

from transformers import AutoTokenizer
import os
from google.colab import userdata

# Base model is configurable; default to a common instruct model
base_model = os.getenv("HF_BASE_MODEL", "meta-llama/Llama-3.1-8B-Instruct")

# Prefer token from Colab secrets for security
hf_token = userdata.get("HF_TOKEN")

tokenizer = AutoTokenizer.from_pretrained(
    base_model,
    use_fast=True,
    token = hf_token,
    trust_remote_code=True,
)
tokenizer.pad_token = tokenizer.eos_token

print("Using base model:", base_model)

"""The required data for training, validation and testing has already been prepared and can be downloaded from Huggingface

"""

import random

# def mask_assistant_tokens_random_amount(
#     input_ids,
#     tokenizer,
#     mask_token="MASK",
#     min_ratio=0.0,
#     max_ratio=1.0,
# ):
#     mask_id = tokenizer.convert_tokens_to_ids(mask_token)

#     assistant_marker = tokenizer.encode(
#         "<|start_header_id|>assistant<|end_header_id|>",
#         add_special_tokens=False
#     )

#     # --- find assistant start ---
#     start = None
#     for i in range(len(input_ids) - len(assistant_marker)):
#         if input_ids[i:i+len(assistant_marker)] == assistant_marker:
#             start = i + len(assistant_marker)
#             break

#     if start is None or start >= len(input_ids):
#         return input_ids, input_ids

#     corrupted = input_ids.copy()
#     labels = input_ids.copy()

#     # 🔥 sample GLOBAL corruption strength per example
#     mask_ratio = random.uniform(min_ratio, max_ratio)

#     # apply token-wise masking
#     for i in range(start, len(input_ids)):
#         if random.random() < mask_ratio:
#             corrupted[i] = mask_id

#     return corrupted, labels

# import random

def mask_assistant_tokens_random_amount(
    input_ids,
    tokenizer,
    mask_token="MASK",
    min_ratio=0.0,
    max_ratio=1.0,
):
    mask_id = tokenizer.convert_tokens_to_ids(mask_token)
    eos_id = tokenizer.eos_token_id

    assistant_marker = tokenizer.encode(
        "<|start_header_id|>assistant<|end_header_id|>",
        add_special_tokens=False
    )

    # --- find assistant start ---
    start = None
    for i in range(len(input_ids) - len(assistant_marker)):
        if input_ids[i:i+len(assistant_marker)] == assistant_marker:
            start = i + len(assistant_marker)
            break

    if start is None or start >= len(input_ids):
        return input_ids, input_ids

    corrupted = input_ids.copy()
    labels = input_ids.copy()

    # --- find the end of the actual answer ---
    # The answer ends at the first eos token after `start`.
    end_of_answer = len(input_ids)
    if eos_id in input_ids[start:]:
        end_of_answer = start + input_ids[start:].index(eos_id)

    # 🔥 sample GLOBAL corruption strength per example
    mask_ratio = random.uniform(min_ratio, max_ratio)

    def apply_exact_ratio_mask(start_idx, end_idx):
        length = end_idx - start_idx
        if length <= 0:
            return

        # Calculate exactly how many tokens to mask based on the ratio
        num_to_mask = int(round(length * mask_ratio))

        # Randomly select exact indices to mask in this segment
        indices = range(start_idx, end_idx)
        mask_indices = random.sample(indices, num_to_mask)

        for idx in mask_indices:
            corrupted[idx] = mask_id

    # 1. Mask exactly `mask_ratio` proportion of the actual answer tokens
    apply_exact_ratio_mask(start, end_of_answer)

    # 2. Mask exactly `mask_ratio` proportion of the remaining EOS/pad tokens
    apply_exact_ratio_mask(end_of_answer, len(input_ids))

    return corrupted, labels

import os
from datasets import load_dataset

dataset = load_dataset(
    "Ruurd/LAD-training",
    split={
        "train": "train[:10000000]",
        "validation": "validation[:200]",
        "test": "test[:200]",
    }
)
train_dataset = dataset["train"]
val_dataset   = dataset["validation"]
test_dataset  = dataset["test"]

def pad_to_chunk(example, chunk_size, pad_id):
    input_ids = example["input_ids"]
    labels = example["labels"]

    length = len(input_ids)

    if length > chunk_size:
        # truncate if needed
        input_ids = input_ids[:chunk_size]
        labels = labels[:chunk_size]
    else:
        pad_len = chunk_size - length
        input_ids = input_ids + [pad_id] * pad_len
        labels = labels + [pad_id] * pad_len  # ignore in loss

    return {
        "input_ids": input_ids,
        "labels": labels,
    }


train_dataset = train_dataset.map(
    lambda x: pad_to_chunk(x, input_size, 128009),
    num_proc=4
)
val_dataset = val_dataset.map(
    lambda x: pad_to_chunk(x, input_size, 128009),
    num_proc=4
)
test_dataset = test_dataset.map(
    lambda x: pad_to_chunk(x, input_size, 128009),
    num_proc=4
)

def preprocess(example):
    input_ids = example["labels"]

    corrupted, labels = mask_assistant_tokens_random_amount(
        input_ids,
        tokenizer
    )

    return {
        "input_ids": corrupted,
        "labels": labels
    }

# train_dataset = train_dataset.map(preprocess, num_proc=4)
# val_dataset = val_dataset.map(preprocess, num_proc=4)
# test_dataset = test_dataset.map(preprocess, num_proc=4)

print(tokenizer.decode(train_dataset[2]['labels']))
print(tokenizer.decode(train_dataset[2]['input_ids']))
tokenizer.encode("MASK", add_special_tokens=False)

"""Below is a viewer to have a look at the training data. Run it a few times to see what kind of noising is applied."""

#@title Diffusion Sample Viewer { display-mode: "form" }

import numpy as np
import ipywidgets as widgets
from IPython.display import display, HTML
import difflib, re

def decode_clean(ids, tokenizer):
    text = tokenizer.decode(ids, skip_special_tokens=False)
    text = re.sub(r'(<\|eot_id\|>)+$', '', text).strip()
    return text

def parse_llama3_chat(text):
    pattern = r'<\|start_header_id\|>(.*?)<\|end_header_id\|>\n(.*?)(?=<\|start_header_id\|>|<\|eot_id\|>|$)'
    segments = []
    for m in re.finditer(pattern, text, re.DOTALL):
        role    = m.group(1).strip()
        content = m.group(2).strip()
        if content:
            segments.append((role, content))
    return segments

def word_diff_html(source, target):
    src_words = source.split()
    tgt_words = target.split()
    matcher   = difflib.SequenceMatcher(None, src_words, tgt_words, autojunk=False)
    src_html, tgt_html = [], []

    def render_words(words, color=None):
        parts = []
        for w in words:
            # Split on MASK boundaries, keeping MASK as a token
            segments = re.split(r'(MASK)', w)
            rendered = ""
            for seg in segments:
                if seg == "MASK":
                    rendered += '<span style="background:#ff9800;color:white;border-radius:3px;padding:1px 5px;font-weight:bold">MASK</span>'
                elif seg:
                    if color:
                        rendered += f'<span style="background:{color};border-radius:3px;padding:1px 4px">{seg}</span>'
                    else:
                        rendered += seg
            parts.append(rendered)
        return " ".join(parts)

    for op, i1, i2, j1, j2 in matcher.get_opcodes():
        if op == "equal":
            src_html.append(render_words(src_words[i1:i2]))
            tgt_html.append(render_words(tgt_words[j1:j2]))
        elif op == "replace":
            src_html.append(render_words(src_words[i1:i2], "#ffcccc"))
            tgt_html.append(render_words(tgt_words[j1:j2], "#ccffcc"))
        elif op == "delete":
            src_html.append(render_words(src_words[i1:i2], "#ffcccc"))
        elif op == "insert":
            tgt_html.append(render_words(tgt_words[j1:j2], "#ccffcc"))

    return " ".join(src_html), " ".join(tgt_html)

ROLE_STYLE = {
    "system":    ("🛠 system",    "#f0f4ff", "#1a73e8"),
    "user":      ("👤 user",      "#f1f3f4", "#3c4043"),
    "assistant": ("🤖 assistant", "#e6f4ea", "#137333"),
}

def render_chat_html(segments_input, segments_label):
    input_dict = dict(segments_input)
    label_dict = dict(segments_label)
    roles      = [r for r, _ in segments_label]

    html = ["""
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;
                font-family:'Google Sans',Arial,sans-serif;font-size:14px">
      <div style="background:#fff3e0;border-radius:8px;padding:10px 14px;
                  font-weight:600;font-size:13px;color:#e65100;text-align:center">
        📥 Noised Input
      </div>
      <div style="background:#e8f5e9;border-radius:8px;padding:10px 14px;
                  font-weight:600;font-size:13px;color:#2e7d32;text-align:center">
        ✅ Clean Label
      </div>
    """]

    for role in roles:
        label_text = label_dict.get(role, "")
        input_text = input_dict.get(role, label_text)
        emoji, _, color = ROLE_STYLE.get(role, ("•", "#fafafa", "#333"))

        if role == "assistant":
            src_html, tgt_html = word_diff_html(input_text, label_text)
        else:
            src_html = tgt_html = input_text.replace("<", "&lt;").replace(">", "&gt;")

        for content, side_bg in [(src_html, "#fff8f0"), (tgt_html, "#f0fff4")]:
            html.append(f"""
            <div style="background:{side_bg};border-radius:8px;padding:12px 14px;
                        border-left:4px solid {color};margin-bottom:4px">
              <div style="font-size:11px;font-weight:700;color:{color};
                          text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px">
                {emoji}
              </div>
              <div style="line-height:1.9;color:#202124;white-space:pre-wrap">{content}</div>
            </div>
            """)

    html.append("</div>")
    html.append("""
    <div style="margin-top:10px;font-size:12px;color:#666;font-family:monospace">
      <span style="background:#ffcccc;border-radius:3px;padding:1px 6px">red</span> = noised word &nbsp;
      <span style="background:#ccffcc;border-radius:3px;padding:1px 6px">green</span> = corrected word &nbsp;
      <span style="background:#ff9800;color:white;border-radius:3px;padding:1px 6px;font-weight:bold">MASK</span> = masked token
    </div>
    """)
    return "".join(html)

# ── Widget ─────────────────────────────────────────────────────────────────
out         = widgets.Output()
button      = widgets.Button(description="🎲 New Sample", button_style="primary",
                             layout=widgets.Layout(width="140px", height="36px"))
index_label = widgets.Label()

def show_sample(_=None):
    out.clear_output(wait=True)
    r      = int(np.random.randint(0, len(train_dataset)))
    sample = train_dataset[r]

    labels_filtered = [t for t in sample["labels"] if t != -100]
    input_text = decode_clean(sample["input_ids"], tokenizer)
    label_text = decode_clean(labels_filtered,     tokenizer)

    segs_input = parse_llama3_chat(input_text)
    segs_label = parse_llama3_chat(label_text)

    index_label.value = f"Sample index: {r}"
    with out:
        display(HTML(render_chat_html(segs_input, segs_label)))

button.on_click(show_sample)
show_sample()
display(widgets.HBox([button, index_label]))
display(out)

"""Define a simple data collator that stacks input_ids and labels into tensors for quick training.

"""

from dataclasses import dataclass
import torch
from typing import List, Dict, Any

@dataclass
class DiffusionDataCollator:
    device: torch.device | None = None

    def __call__(self, features: List[Dict[str, Any]]):
        batch_input_ids = torch.stack([torch.tensor(f["input_ids"], dtype=torch.long) for f in features])
        batch_labels = torch.stack([torch.tensor(f["labels"], dtype=torch.long) for f in features])

        if self.device is not None:
            batch_input_ids = batch_input_ids.to(self.device, non_blocking=True)
            batch_labels = batch_labels.to(self.device, non_blocking=True)

        return {"input_ids": batch_input_ids, "labels": batch_labels}

# Initialize the collator (Trainer will move tensors if device_map is used)
data_collator = DiffusionDataCollator(device=None)

from dataclasses import dataclass
from typing import List, Dict, Any

import torch

## Adaptive length data collator

@dataclass
class DiffusionDataCollator:
    eos_token_id: int
    device: torch.device | None = None
    pad_to_multiple_of: int | None = None

    def _remove_extra_eos_padding(
        self,
        input_ids: list[int],
        labels: list[int],
    ) -> tuple[list[int], list[int]]:
        """
        Remove repeated EOS padding while preserving one EOS token
        marking the actual end of the sequence.
        """
        if len(input_ids) != len(labels):
            raise ValueError(
                "input_ids and labels must have equal lengths."
            )

        end = len(input_ids)

        # Remove trailing EOS tokens, but preserve one final EOS.
        while (
            end > 1
            and input_ids[end - 1] == self.eos_token_id
            and input_ids[end - 2] == self.eos_token_id
        ):
            end -= 1

        return input_ids[:end], labels[:end]

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:

        trimmed_features = []

        for feature in features:
            input_ids = list(feature["input_ids"])
            labels = list(feature["labels"])

            input_ids, labels = self._remove_extra_eos_padding(
                input_ids,
                labels,
            )

            trimmed_features.append(
                {
                    "input_ids": input_ids,
                    "labels": labels,
                }
            )

        batch_max_length = max(
            len(feature["input_ids"])
            for feature in trimmed_features
        )

        if self.pad_to_multiple_of is not None:
            multiple = self.pad_to_multiple_of
            batch_max_length = (
                (batch_max_length + multiple - 1)
                // multiple
                * multiple
            )

        batch_input_ids = []
        batch_labels = []

        for feature in trimmed_features:
            input_ids = feature["input_ids"]
            labels = feature["labels"]

            padding_length = batch_max_length - len(input_ids)

            # LLaDA-style EOS padding: these remain ordinary targets.
            padded_input_ids = (
                input_ids
                + [self.eos_token_id] * padding_length
            )

            padded_labels = (
                labels
                + [self.eos_token_id] * padding_length
            )

            batch_input_ids.append(padded_input_ids)
            batch_labels.append(padded_labels)

        batch_input_ids = torch.tensor(
            batch_input_ids,
            dtype=torch.long,
        )

        batch_labels = torch.tensor(
            batch_labels,
            dtype=torch.long,
        )

        if self.device is not None:
            batch_input_ids = batch_input_ids.to(
                self.device,
                non_blocking=True,
            )
            batch_labels = batch_labels.to(
                self.device,
                non_blocking=True,
            )

        return {
            "input_ids": batch_input_ids,
            "labels": batch_labels,
        }


data_collator = DiffusionDataCollator(
    eos_token_id=tokenizer.eos_token_id,
    device=None,
    # Optional Tensor Core-friendly sequence lengths:
    pad_to_multiple_of=8,
)

from dataclasses import dataclass
from typing import List, Dict, Any
import random
import torch

@dataclass
class DiffusionDataCollator:
    eos_token_id: int
    device: torch.device | None = None
    pad_to_multiple_of: int | None = None
    multi_turn_prob: float = 0.5  # Probability of prepending prior turn context
    max_history_turns: int = 2     # Max prior turns to prepend (1 or 2)

    def _remove_extra_eos_padding(
        self,
        input_ids: list[int],
        labels: list[int],
    ) -> tuple[list[int], list[int]]:
        """
        Remove repeated EOS padding while preserving one EOS token
        marking the actual end of the sequence.
        """
        if len(input_ids) != len(labels):
            raise ValueError("input_ids and labels must have equal lengths.")

        end = len(input_ids)
        while (
            end > 1
            and input_ids[end - 1] == self.eos_token_id
            and input_ids[end - 2] == self.eos_token_id
        ):
            end -= 1

        return input_ids[:end], labels[:end]

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:

        # 1. Clean individual features first
        cleaned_features = []
        for feature in features:
            input_ids, labels = self._remove_extra_eos_padding(
                list(feature["input_ids"]),
                list(feature["labels"]),
            )
            cleaned_features.append({
                "input_ids": input_ids,
                "labels": labels,
            })

        batch_size = len(cleaned_features)
        combined_features = []

        # 2. Combine history turns with target turns
        for i, target_feature in enumerate(cleaned_features):
            # Decide whether to prepend history for this sample
            num_history = 0
            if (
                self.multi_turn_prob > 0
                and batch_size > 1
                and random.random() < self.multi_turn_prob
            ):
                num_history = random.randint(1, min(self.max_history_turns, batch_size - 1))

            combined_input_ids = []
            combined_labels = []

            if num_history > 0:
                # Randomly pick prior features from the batch (excluding current target)
                available_indices = [idx for idx in range(batch_size) if idx != i]
                history_indices = random.sample(available_indices, num_history)

                for h_idx in history_indices:
                    hist_feature = cleaned_features[h_idx]
                    # CRITICAL: For historical turns, use the ground-truth labels
                    # for BOTH input_ids and labels (clean context).
                    clean_context = hist_feature["labels"]
                    combined_input_ids.extend(clean_context)
                    combined_labels.extend(clean_context)

            # Append the actual target turn (noised input_ids, target labels)
            combined_input_ids.extend(target_feature["input_ids"])
            combined_labels.extend(target_feature["labels"])

            combined_features.append({
                "input_ids": combined_input_ids,
                "labels": combined_labels,
            })

        # 3. Calculate max length for padding
        batch_max_length = max(
            len(feature["input_ids"]) for feature in combined_features
        )

        if self.pad_to_multiple_of is not None:
            multiple = self.pad_to_multiple_of
            batch_max_length = (
                (batch_max_length + multiple - 1)
                // multiple
                * multiple
            )

        # 4. Pad batch sequences
        batch_input_ids = []
        batch_labels = []

        for feature in combined_features:
            input_ids = feature["input_ids"]
            labels = feature["labels"]

            padding_length = batch_max_length - len(input_ids)

            padded_input_ids = input_ids + [self.eos_token_id] * padding_length
            padded_labels = labels + [self.eos_token_id] * padding_length

            batch_input_ids.append(padded_input_ids)
            batch_labels.append(padded_labels)

        # 5. Convert to tensors
        batch_input_ids_tensor = torch.tensor(batch_input_ids, dtype=torch.long)
        batch_labels_tensor = torch.tensor(batch_labels, dtype=torch.long)

        if self.device is not None:
            batch_input_ids_tensor = batch_input_ids_tensor.to(
                self.device, non_blocking=True
            )
            batch_labels_tensor = batch_labels_tensor.to(
                self.device, non_blocking=True
            )

        return {
            "input_ids": batch_input_ids_tensor,
            "labels": batch_labels_tensor,
        }

data_collator = DiffusionDataCollator(
    eos_token_id=tokenizer.eos_token_id,
    device=None,
    pad_to_multiple_of=8,
    multi_turn_prob=0.3,     # 50% chance to construct a multi-turn conversation
    max_history_turns=2,      # Prepend 1 or 2 prior turns
)

"""Clear CUDA cache before heavy model setup.

"""

torch.cuda.empty_cache()

"""Define the custom Llama-based denoising model with LoRA adapters and initialize it (optionally loading from checkpoint).

"""

# import torch
import torch.nn as nn
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer, PreTrainedModel, PretrainedConfig
from transformers.models.llama.modeling_llama import LlamaAttention
import matplotlib.pyplot as plt
from torch.amp import autocast
from torch.nn import Embedding
import torch.nn.functional as F
import torchinfo
from peft import LoraConfig, get_peft_model, PeftModel, LoraModel
import importlib
from typing import Callable, List, Optional, Tuple, Union
import os
from contextlib import nullcontext

import torch
import torch.nn as nn
from transformers import (
    AutoConfig,
    AutoModelForCausalLM,
    PreTrainedModel,
)
from peft import LoraConfig, get_peft_model


class CustomTransformerConfig(PretrainedConfig):
    def __init__(self, vocab_size=128256, hidden_size=4096, num_layers=32, num_heads=32, prediction_chunk=256, dropout=0,
                 max_position_embeddings=4096, masking_type="bidirectional", **kwargs):
        super().__init__(**kwargs)
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.num_heads = num_heads
        self.dropout = dropout
        self.prediction_chunk = prediction_chunk
        self.max_position_embeddings = max_position_embeddings
        self.input_size = prediction_chunk
        self.masking_type = masking_type

class CustomTransformerModel(PreTrainedModel):
    # config_class = CustomTransformerConfig

    def __init__(self, config):
        super().__init__(config)

        llama_config = AutoConfig.from_pretrained(
            base_model,
            token=os.environ.get("HF_TOKEN"),
        )

        # Disable Llama's built-in causal attention.
        llama_config.is_causal = False
        llama_config.use_cache = False

        self.llama = AutoModelForCausalLM.from_pretrained(
            base_model,
            config=llama_config,
            token=os.environ.get("HF_TOKEN"),
            attn_implementation="sdpa",
            dtype=torch.float16
        )

        self.llama.resize_token_embeddings(config.vocab_size)

        # Freeze the base model.
        for param in self.llama.parameters():
            param.requires_grad = False

        target_modules = ["q_proj", "v_proj"]

        lora_config = LoraConfig(
            r=4096,
            lora_alpha=4096,
            lora_dropout=0.0,
            target_modules=target_modules,
            bias="none",
            task_type=None
        )

        self.llama = get_peft_model(
            self.llama,
            lora_config,
        )

        self.llama.print_trainable_parameters()

    def forward(
        self,
        input_ids,
        labels=None,
        attention_mask=None,
        **kwargs,
    ):
        batch_size, seq_len = input_ids.shape
        device = input_ids.device

        masking_type = getattr(
            self.config,
            "masking_type",
            "bidirectional",
        )

        # Use all positions by default.
        if attention_mask is None:
            padding_mask = torch.ones(
                batch_size,
                seq_len,
                dtype=torch.bool,
                device=device,
            )
        else:
            padding_mask = attention_mask.to(
                device=device,
                dtype=torch.bool,
            )

        if masking_type == "bidirectional":
            # A normal 2-D attention mask plus is_causal=False gives
            # unrestricted bidirectional attention.
            model_attention_mask = None
            is_causal = False

        elif masking_type == "bidirectional_masked":
            # True means attention is allowed.
            base_mask = torch.ones(
                seq_len,
                seq_len,
                dtype=torch.bool,
                device=device,
            )

            # Prevent each token from attending to itself.
            base_mask.fill_diagonal_(False)

            # Apply the padding/key mask.
            model_attention_mask = (
                base_mask.unsqueeze(0)
                & padding_mask.unsqueeze(1)
            )

            # Shape: batch, heads, query positions, key positions.
            model_attention_mask = model_attention_mask.unsqueeze(1)

            is_causal = False

        elif masking_type == "unidirectional":
            # Let Transformers/SDPA construct the causal component.
            model_attention_mask = padding_mask
            is_causal = True

        else:
            raise ValueError(
                f"Unknown masking type: {masking_type}"
            )

        # Prevent duplicate/conflicting keyword arguments.
        kwargs.pop("use_cache", None)
        kwargs.pop("is_causal", None)
        kwargs.pop("output_hidden_states", None)

        autocast_context = (
            torch.autocast(
                device_type="cuda",
                dtype=torch.float16,
            )
            if input_ids.device.type == "cuda"
            else nullcontext()
        )

        with autocast_context:
            outputs = self.llama(
                input_ids=input_ids,
                attention_mask=model_attention_mask,
                output_hidden_states=False,
                use_cache=False,
                is_causal=is_causal,
                **kwargs,
            )

        logits = outputs.logits[
            :, :, :self.config.vocab_size
        ]

        logits = logits.reshape(
            batch_size,
            seq_len,
            self.config.vocab_size,
        )

        loss = None

        if labels is not None:
            expected_shape = (batch_size, seq_len)

            assert labels.shape == expected_shape, (
                f"Labels shape mismatch: expected {expected_shape}, "
                f"got {tuple(labels.shape)}"
            )

            # Same-position prediction: no autoregressive shift.
            loss_fct = nn.CrossEntropyLoss()

            loss = loss_fct(
                logits.reshape(
                    -1,
                    self.config.vocab_size,
                ),
                labels.reshape(-1),
            )

        if loss is not None:
            return {
                "loss": loss,
                "logits": logits,
            }

        return {
            "logits": logits,
        }

def reset_weights(model):
    for module in model.modules():
        if hasattr(module, "reset_parameters"):  # Check if the layer has reset_parameters()
            module.reset_parameters()
    return model

# Initialize model
new = True
# Initialize Accelerator
accelerator = Accelerator()
# Move model and data to the right device (CPU or GPU)
device = accelerator.device
print(f"Using device: {device}")
# device = "cuda" if torch.cuda.is_available() else "cpu"
if new:
    config = CustomTransformerConfig(vocab_size=len(tokenizer), device=device)
    model = CustomTransformerModel(config)
    model.to(device)
else:
    checkpoint_path = "./drive/MyDrive/diffusion-model-llama-3.2-1B-finetuned-1024lora-instruct_step20000.pt"
    # Load the model, specifying the PyTorch format and dtype
    config = CustomTransformerConfig(vocab_size=len(tokenizer), device = device)  # Ensure correct vocab size
    # model = CustomTransformerModel(config)
    # model.load_state_dict(torch.load("diffusion_model.pth", weights_only = False))

    ## This is really annoying but necessary to load an old model with only the weights.
    # Get missing classes/functions
    torch.serialization.clear_safe_globals()
    # Step 1: Find missing classes
    unsafe_globals = torch.serialization.get_unsafe_globals_in_checkpoint(checkpoint_path)

    # Step 2: Extract missing class names
    missing_class_names = [name.split(".")[-1] for name in unsafe_globals]

    # Step 3: Try importing from `globals()`, and also attempt dynamic import for Hugging Face classes
    safe_classes = [cls for name, cls in globals().items() if name in missing_class_names]

    for class_path in unsafe_globals:
        try:
            module_name, class_name = class_path.rsplit(".", 1)
            module = importlib.import_module(module_name)
            cls = getattr(module, class_name)
            safe_classes.append(cls)
        except (ImportError, AttributeError) as e:
            print(f"⚠️ Warning: Could not import {class_path} - {e}")

    # Step 4: Register all safe classes
    torch.serialization.add_safe_globals(safe_classes)

    # Step 5: Load the model safely
    model = torch.load(checkpoint_path, weights_only=True)

    # model = model.to(torch.float16) # DO NOT USE THIS, JUST LEFT IT AS A WARNING

    # state_dict = torch.load(checkpoint_path, weights_only=True, map_location=device)
    # model.load_state_dict(state_dict)

    # Disable dropout
    model = disable_dropout(model)

    # Move to GPU if available
    model.to(device)

    model.train()


    print("✅ Model successfully loaded from checkpoint:", checkpoint_path)

# Remove problematic attributes from config
if hasattr(model.config, "device"):
    del model.config.device

print(torchinfo.summary(model,depth = 3))

# def unfreeze_last_n_layers(model, n):
#     layers = model.llama.base_model.model.model.layers
#     for layer in layers[-n:]:
#         for param in layer.parameters():
#             param.requires_grad = True

# unfreeze_last_n_layers(model, n=1)

# print(torchinfo.summary(model,depth = 3))

# for name, param in model.named_parameters():
#     if param.requires_grad:
#         print(name)

model.llama.print_trainable_parameters()

# # Unfreeze the language-model head.
# for param in model.llama.lm_head.parameters():
#     param.requires_grad = True

# Unfreeze normalization layers.
for name, param in model.llama.named_parameters():
    if "norm" in name.lower():
        param.requires_grad = True

for name, param in model.named_parameters():
    if param.requires_grad and param.dtype == torch.float16:
        param.data = param.data.float()

model.llama.print_trainable_parameters()

"""Free cached CUDA memory.

"""

torch.cuda.empty_cache()
gc.collect()

"""Brief training loop setup with callbacks, logging, and evaluation sampling.

"""

import os
from pathlib import Path

base_name  = Path(base_model).name if "/" in base_model else base_model
lora_r     = getattr(getattr(model, "config", {}), "lora_r", "na")
run_name   = f"diffusion-{base_name}-r{lora_r}"

output_dir     = os.path.join("./outputs",     run_name)
checkpoint_dir = os.path.join("./checkpoints", run_name)
os.makedirs(output_dir,     exist_ok=True)
os.makedirs(checkpoint_dir, exist_ok=True)

print(f"📂 Run name     : {run_name}")
print(f"📂 Output dir   : {output_dir}")
print(f"📂 Checkpoint   : {checkpoint_dir}")

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from IPython.display import display, clear_output
from transformers import TrainerCallback, TrainerState, TrainerControl

plot_output = widgets.Output()

class LivePlotCallback(TrainerCallback):
    """Draws a live loss curve that updates in-place every eval step."""

    def __init__(self):
        self.train_steps, self.train_losses   = [], []
        self.eval_steps,  self.eval_losses    = [], []
        self.best_eval_loss = float("inf")
        self.fig, self.ax = plt.subplots(figsize=(9, 4))
        plt.close(self.fig)  # don't show immediately

    def on_log(self, args, state: TrainerState, control: TrainerControl, logs=None, **kwargs):
        if logs is None:
            return
        step = state.global_step
        if "loss" in logs:
            self.train_steps.append(step)
            self.train_losses.append(logs["loss"])
        if "eval_loss" in logs:
            self.eval_steps.append(step)
            self.eval_losses.append(logs["eval_loss"])
        self._redraw()

    def _redraw(self):
        self.ax.clear()
        self.ax.set_yscale('log')

        if self.train_losses:
            self.ax.plot(self.train_steps, self.train_losses,
                         label="Train loss", color="#1a73e8", linewidth=1.5, alpha=0.8)
        if self.eval_losses:
            self.ax.plot(self.eval_steps, self.eval_losses,
                         label="Eval loss", color="#e8430a", linewidth=2,
                         marker="o", markersize=4)
            best = min(self.eval_losses)
            best_step = self.eval_steps[self.eval_losses.index(best)]
            self.ax.axvline(best_step, color="#e8430a", linestyle="--",
                            alpha=0.4, label=f"Best eval ({best:.4f})")

        self.ax.set_xlabel("Step")
        self.ax.set_ylabel("Loss")
        self.ax.set_title("Training Progress")
        self.ax.legend(loc="upper right")
        self.ax.grid(True, alpha=0.3)
        self.ax.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))
        self.fig.tight_layout()

        with plot_output:
            clear_output(wait=True)
            display(self.fig)

plot_callback = LivePlotCallback()
print("LivePlotCallback ready")

import torch, re, difflib
import torch.nn.functional as F
import numpy as np
from IPython.display import display, HTML
from transformers import TrainerCallback, TrainerState, TrainerControl

# ── Reuse the HTML rendering helpers from the data viewer ──────────────────
# (parse_llama3_chat, word_diff_html, render_chat_html must already be defined)

sample_output = widgets.Output()

class DenoisingSampleCallback(TrainerCallback):
    """At each eval step, show a random denoising example with the diff viewer."""

    def __init__(self, dataset, tokenizer, temperature: float = 0.3):
        self.dataset     = dataset
        self.tokenizer   = tokenizer
        self.temperature = temperature

    def on_evaluate(self, args, state: TrainerState, control: TrainerControl, model=None, **kwargs):
        if model is None or len(self.dataset) == 0:
            return
        model.eval()
        device = next(model.parameters()).device

        idx    = int(np.random.randint(0, len(self.dataset)))
        sample = self.dataset[idx]

        input_ids = torch.tensor(sample["input_ids"], dtype=torch.long).unsqueeze(0).to(device)
        labels    = torch.tensor(sample["labels"],    dtype=torch.long).unsqueeze(0).to(device)

        with torch.no_grad():
            logits = model(input_ids=input_ids)["logits"]

        probs       = F.softmax(logits / self.temperature, dim=-1).clamp(min=1e-8)
        predictions = torch.multinomial(probs.squeeze(0), num_samples=1).squeeze(-1)

        # Decode all three sequences
        labels_filtered = [t for t in labels[0].tolist() if t != -100]
        input_text  = decode_clean(input_ids[0].tolist(), tokenizer)
        label_text  = decode_clean(labels_filtered,       tokenizer)
        pred_text   = decode_clean(predictions.tolist(),  tokenizer)

        segs_input = parse_llama3_chat(input_text)
        segs_label = parse_llama3_chat(label_text)
        segs_pred  = parse_llama3_chat(pred_text)

        # Build a three-column view: input | prediction | label
        html = [f"""
        <div style="font-family:'Google Sans',Arial,sans-serif;font-size:13px">
        <div style="font-weight:700;font-size:15px;margin-bottom:10px">
          🔍 Denoising Sample — Step {state.global_step}
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px">
          <div style="background:#fff3e0;border-radius:8px;padding:8px 12px;
                      font-weight:600;color:#e65100;text-align:center">📥 Noised Input</div>
          <div style="background:#e8f0fe;border-radius:8px;padding:8px 12px;
                      font-weight:600;color:#1a73e8;text-align:center">🤖 Model Output</div>
          <div style="background:#e8f5e9;border-radius:8px;padding:8px 12px;
                      font-weight:600;color:#2e7d32;text-align:center">✅ Clean Label</div>
        """]

        input_dict = dict(segs_input)
        label_dict = dict(segs_label)
        pred_dict  = dict(segs_pred)
        roles      = [r for r, _ in segs_label]

        ROLE_STYLE = {
            "system":    ("🛠 system",    "#1a73e8"),
            "user":      ("👤 user",      "#3c4043"),
            "assistant": ("🤖 assistant", "#137333"),
        }

        for role in roles:
            label_text_r = label_dict.get(role, "")
            input_text_r = input_dict.get(role, label_text_r)
            pred_text_r  = pred_dict.get(role,  "")
            emoji, color = ROLE_STYLE.get(role, ("•", "#333"))

            if role == "assistant":
                inp_html, _        = word_diff_html(input_text_r, label_text_r)
                pred_html, lbl_html = word_diff_html(pred_text_r,  label_text_r)
            else:
                inp_html = lbl_html = input_text_r.replace("<","&lt;").replace(">","&gt;")
                pred_html = pred_text_r.replace("<","&lt;").replace(">","&gt;")

            for content, bg in [
                (inp_html,  "#fff8f0"),
                (pred_html, "#f0f4ff"),
                (lbl_html,  "#f0fff4"),
            ]:
                html.append(f"""
                <div style="background:{bg};border-radius:8px;padding:10px 12px;
                            border-left:4px solid {color}">
                  <div style="font-size:10px;font-weight:700;color:{color};
                              text-transform:uppercase;margin-bottom:4px">{emoji}</div>
                  <div style="line-height:1.8;color:#202124;white-space:pre-wrap">{content}</div>
                </div>""")

        html.append("</div>")
        html.append("""
        <div style="margin-top:8px;font-size:11px;color:#666;font-family:monospace">
          <span style="background:#ffcccc;border-radius:3px;padding:1px 5px">red</span> = differs from label &nbsp;
          <span style="background:#ccffcc;border-radius:3px;padding:1px 5px">green</span> = matches label
        </div></div>""")

        with sample_output:
            clear_output(wait=True)
            display(HTML("".join(html)))


class BestModelCallback(TrainerCallback):
    """Save the model only when eval loss improves."""

    def __init__(self, save_dir: str):
        self.save_dir        = save_dir
        self.best_eval_loss  = float("inf")
        os.makedirs(save_dir, exist_ok=True)

    def on_evaluate(self, args, state: TrainerState, control: TrainerControl, metrics=None, **kwargs):
        if metrics is None:
            return
        eval_loss = metrics.get("eval_loss", float("inf"))
        if eval_loss < self.best_eval_loss:
            self.best_eval_loss = eval_loss
            model_to_save = kwargs.get("model")
            if model_to_save is not None:
                print(f"\n💾 New best eval loss {eval_loss:.4f} — saving to {self.save_dir}")
                model_to_save.save_pretrained(self.save_dir)


sample_callback     = DenoisingSampleCallback(dataset=test_dataset, tokenizer=tokenizer)
best_model_callback = BestModelCallback(save_dir=os.path.join(checkpoint_dir, "best"))
print("✅ DenoisingSampleCallback ready")
print("✅ BestModelCallback ready")
train_dataset_shuffled = train_dataset.shuffle(seed=42)

from transformers import Trainer, TrainingArguments

steps_taken = 0

torch.cuda.empty_cache()

training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=int(os.getenv("TRAIN_BATCH_SIZE", "8")),
    per_device_eval_batch_size=int(os.getenv("TRAIN_BATCH_SIZE", "8")),
    gradient_accumulation_steps=1,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="no",           # handled by BestModelCallback
    logging_steps=10,
    report_to=[],                 # no W&B
    weight_decay=0.01,
    learning_rate=1e-5,
    warmup_steps=100,
    # bf16=True,
    # fp16=False,
    fp16=True,
    lr_scheduler_type="constant_with_warmup",
    remove_unused_columns=False,
    dataloader_num_workers=8,
    dataloader_pin_memory=True,
    max_grad_norm=0.5,
)

val_subset = val_dataset.select(range(min(len(val_dataset), 200)))

class OffsetCallbackWrapper(TrainerCallback):
    def __init__(self, original_callback, step_offset):
        self.original = original_callback
        self.offset = step_offset

    def _with_offset(self, method_name, args, state, control, **kwargs):
        # Temporarily fake the global step for the callback
        original_step = state.global_step
        state.global_step = original_step + self.offset

        # Trigger the original callback
        if hasattr(self.original, method_name):
            getattr(self.original, method_name)(args, state, control, **kwargs)

        # Revert back so HF Trainer continues normally
        state.global_step = original_step

    def on_log(self, args, state, control, **kwargs):
        self._with_offset("on_log", args, state, control, **kwargs)

    def on_evaluate(self, args, state, control, **kwargs):
        self._with_offset("on_evaluate", args, state, control, **kwargs)

    def on_step_end(self, args, state, control, **kwargs):
        self._with_offset("on_step_end", args, state, control, **kwargs)

# Use this only when you have interrupted training to avoid training on the same data again
batch_size = 8
steps_taken = 0 ## USUALLY SET THIS TO ZERO
samples_processed = steps_taken * batch_size
total_samples = len(train_dataset_shuffled)
remaining_dataset = train_dataset_shuffled.select(range(samples_processed, total_samples))

wrapped_plot = OffsetCallbackWrapper(plot_callback, step_offset=steps_taken)
wrapped_sample = OffsetCallbackWrapper(sample_callback, step_offset=steps_taken)

# 3. Initialize Trainer with the remaining data and the wrapped callbacks
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=remaining_dataset,
    eval_dataset=val_subset,
    data_collator=data_collator,
    callbacks=[wrapped_plot, wrapped_sample], # Use the wrapped versions!
)


# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset=train_dataset_shuffled,
#     eval_dataset=val_subset,
#     data_collator=data_collator,
#     callbacks=[plot_callback, sample_callback], # Include BestModelCallback if you want to save the model
# )

display(plot_output)
display(sample_output)
trainer.train()

# Run another random example
display(sample_output)
sample_callback.on_evaluate(args=None, state=type('', (), {'global_step': 'inference'})(),
                             control=None, model=model)

from collections import defaultdict
import numpy as np

def build_ngram_table_from_dataset(dataset, n=3, max_samples=None):
    """
    Build n-gram log-prob table from a tokenized dataset.

    dataset[i]['labels'] must be a list of token IDs.
    """
    counts = defaultdict(int)
    context_counts = defaultdict(int)

    total_samples = len(dataset) if max_samples is None else min(len(dataset), max_samples)

    for i in range(total_samples):
        tokens = dataset[i]["labels"]

        # Optional: remove -100 (common in HF labels)
        tokens = [t for t in tokens if t != -100]

        if len(tokens) < n:
            continue

        for j in range(len(tokens) - n + 1):
            ngram = tuple(tokens[j:j+n])
            context = tuple(tokens[j:j+n-1])

            counts[ngram] += 1
            context_counts[context] += 1

    # Convert to log-probs
    table = {}
    for ngram, c in counts.items():
        context = ngram[:-1]
        table[ngram] = np.log(c / context_counts[context])

    return table

N_GRAM_N = 3  # or your slider value

ngram_table = build_ngram_table_from_dataset(
    train_dataset,
    n=N_GRAM_N,
    max_samples=1000  # optional speed limit
)

#@title 💬 Interactive Denoising Inference { display-mode: "form" }
import torch
import torch.nn.functional as F
import numpy as np
import re
from collections import defaultdict
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets

# ── Config ────────────────────────────────────────────────────────────────────
QUESTION          = "What do you know about Amsterdam?"  #@param {type:"string"}
NUM_STEPS         = 32    #@param {type:"slider", min:1, max:256, step:1}
NOISE_LEVEL       = 0.5   #@param {type:"slider", min:0.0, max:1.0, step:0.05}
TEMPERATURE       = 0.5   #@param {type:"slider", min:0.1, max:2.0, step:0.1}
TOP_K             = 5    #@param {type:"slider", min:1, max:100, step:1}
PERMANENT_UNMASK  = False  #@param {type:"boolean"}
CONFIDENCE_GUIDED = False  #@param {type:"boolean"}
PROPORTIONAL_UNMASK= True  #@param {type:"boolean"}
MAX_TOKENS         = 64   #@param {type:"slider", min:1, max:512, step:1}

USE_NGRAM_GRAMMAR = False  #@param {type:"boolean"}
GRAMMAR_WEIGHT         = 0.95   #@param {type:"slider", min:0.0, max:2.0, step:0.05}
REMOVE_STUCK_REPETITIONS = True #@param {type:"boolean"}

# ── Simple Bigram Table (lazy + cached) ───────────────────────────────────────
bigram_cache = defaultdict(lambda: defaultdict(float))

def get_bigram_score(prev_token, curr_token):
    # Very cheap heuristic instead of full LM:
    # reward space-consistent / punctuation-consistent transitions
    prev = tokenizer.decode([prev_token])
    curr = tokenizer.decode([curr_token])

    score = 0.0

    # simple heuristics (fast)
    if prev.endswith(" ") and curr.startswith(" "):
        score -= 0.5
    if prev.endswith((".", "!", "?")):
        if not curr.strip().startswith((" ", "\n")):
            score -= 0.3
    if prev.strip() == "" and curr.strip() == "":
        score -= 0.5

    # encourage letter continuity
    if prev and curr and prev[-1].isalpha() and curr[0].isalpha():
        score += 0.1

    return score

# ── Helpers ───────────────────────────────────────────────────────────────────
def format_prompt(question):
    return (
        "<|begin_of_text|>\n"
        "<|start_header_id|>system<|end_header_id|>\n"
        "You are a helpful assistant.\n"
        "<|eot_id|>\n"
        "<|start_header_id|>user<|end_header_id|>\n"
        f"{question}\n"
        "<|eot_id|>\n"
        "<|start_header_id|>assistant<|end_header_id|>\n"
    )

def find_answer_start(input_ids):
    marker = tokenizer.encode(
        "<|start_header_id|>assistant<|end_header_id|>\n",
        add_special_tokens=False
    )
    for i in range(len(input_ids) - len(marker) + 1):
        if input_ids[i:i+len(marker)] == marker:
            return i + len(marker)
    return None

def top_k_filter(probs, k):
    topk_vals, topk_idx = torch.topk(probs, k)
    mask = torch.zeros_like(probs).scatter_(-1, topk_idx, 1.0)
    filtered = probs * mask
    filtered = filtered / filtered.sum(dim=-1, keepdim=True)
    return filtered, topk_idx, topk_vals

# ── N-GRAM SCORING ────────────────────────────────────────────────────────────
def ngram_score(sequence, pos, candidate, n):
    """
    Score candidate token at position pos using n-gram context.
    Uses left context only (fast + causal approximation).
    """
    if pos < n - 1:
        return 0.0  # not enough context

    context = sequence[pos - (n - 1):pos]
    ngram = tuple(context + [candidate])
    return ngram_table.get(ngram, -8.0)


def apply_ngram_grammar_filter(probs, input_ids, n):
    """
    Reweight probabilities using n-gram grammar scores.
    Only applied to TOP-K tokens (already filtered).
    """
    probs_np = probs.cpu().numpy()
    new_probs = np.zeros_like(probs_np)

    for i in range(len(input_ids)):
        token_probs = probs_np[i]
        candidates = np.where(token_probs > 0)[0]

        scores = []
        for tok in candidates:
            score = ngram_score(input_ids, i, tok, n)
            scores.append(score)

        scores = np.array(scores)
        scores = np.exp(scores)  # back to prob space

        weighted = token_probs[candidates] * scores
        if weighted.sum() > 0:
            weighted /= weighted.sum()

        new_probs[i, candidates] = weighted

    return torch.tensor(new_probs, device=probs.device)

def grammar_aware_sample(probs, topk_idx, topk_vals, input_ids, answer_start):
    seq_len = probs.shape[0]
    generated = []

    for i in range(seq_len):
        if i < answer_start:
            generated.append(input_ids[i])
            continue

        candidates = topk_idx[i]
        candidate_probs = topk_vals[i]

        best_token = None
        best_score = -1e9

        for tok, p in zip(candidates, candidate_probs):
            tok = tok.item()
            p = p.item()

            score = np.log(p + 1e-8)

            if GRAMMAR_AWARE_DECODING and len(generated) > 0:
                prev_tok = generated[-1]
                score += GRAMMAR_WEIGHT * get_bigram_score(prev_tok, tok)

            if score > best_score:
                best_score = score
                best_token = tok

        generated.append(best_token)

    return generated

def noising_schedule(step, total_steps, noise_level):
    frac = 1.0 - (step / total_steps)
    return noise_level * frac

def renoise(tokens, answer_start, mask_token_id, noise_frac, confidences=None, frozen_indices=None, permanent_unmask=True, confidence_guided=True, proportional_unmask=True, eos_id=None):
    noised = tokens.copy()
    answer_indices = list(range(answer_start, len(tokens)))

    num_to_mask = max(1, int(noise_frac * len(answer_indices)))
    num_to_keep = len(answer_indices) - num_to_mask

    # Find the boundary for proportional splitting
    end_of_answer_idx = len(tokens)
    if eos_id is not None and eos_id in tokens[answer_start:]:
        end_of_answer_idx = answer_start + tokens[answer_start:].index(eos_id)

    normal_indices = [i for i in answer_indices if i < end_of_answer_idx]
    pad_indices = [i for i in answer_indices if i >= end_of_answer_idx]
    use_proportional = proportional_unmask and len(normal_indices) > 0 and len(pad_indices) > 0

    if permanent_unmask and frozen_indices is not None:
        shortfall = num_to_keep - len(frozen_indices)

        if shortfall > 0:
            if use_proportional:
                # Calculate how many normal vs pad tokens SHOULD be frozen in total
                ratio_normal = len(normal_indices) / len(answer_indices)
                target_normal_frozen = int(round(num_to_keep * ratio_normal))
                target_pad_frozen = num_to_keep - target_normal_frozen

                current_normal_frozen = len([i for i in frozen_indices if i < end_of_answer_idx])
                current_pad_frozen = len([i for i in frozen_indices if i >= end_of_answer_idx])

                shortfall_normal = max(0, target_normal_frozen - current_normal_frozen)
                shortfall_pad = max(0, target_pad_frozen - current_pad_frozen)

                unfrozen_normal = [i for i in normal_indices if i not in frozen_indices]
                unfrozen_pad = [i for i in pad_indices if i not in frozen_indices]

                shortfall_normal = min(shortfall_normal, len(unfrozen_normal))
                shortfall_pad = min(shortfall_pad, len(unfrozen_pad))

                # Correct for rounding errors if one bucket maxed out
                remaining = shortfall - (shortfall_normal + shortfall_pad)
                if remaining > 0:
                    if shortfall_normal < len(unfrozen_normal):
                        shortfall_normal += remaining
                    elif shortfall_pad < len(unfrozen_pad):
                        shortfall_pad += remaining

                def freeze_tokens(unfrozen_pool, count):
                    if count <= 0 or not unfrozen_pool: return
                    if confidence_guided and confidences is not None:
                        pool_confs = [confidences[i] for i in unfrozen_pool]
                        best_idx = np.argsort(pool_confs)[-count:]
                        for idx in best_idx:
                            frozen_indices.add(unfrozen_pool[idx])
                    else:
                        rand_idx = np.random.choice(len(unfrozen_pool), size=count, replace=False)
                        for idx in rand_idx:
                            frozen_indices.add(unfrozen_pool[idx])

                freeze_tokens(unfrozen_normal, shortfall_normal)
                freeze_tokens(unfrozen_pad, shortfall_pad)

            else:
                unfrozen_indices = [i for i in answer_indices if i not in frozen_indices]
                shortfall = min(shortfall, len(unfrozen_indices))

                if shortfall > 0 and unfrozen_indices:
                    if confidence_guided and confidences is not None:
                        unfrozen_confs = [confidences[i] for i in unfrozen_indices]
                        best_local_idx = np.argsort(unfrozen_confs)[-shortfall:]
                        for idx in best_local_idx:
                            frozen_indices.add(unfrozen_indices[idx])
                    else:
                        random_local_idx = np.random.choice(len(unfrozen_indices), size=shortfall, replace=False)
                        for idx in random_local_idx:
                            frozen_indices.add(unfrozen_indices[idx])

        # Mask everything not frozen
        for idx in answer_indices:
            if idx not in frozen_indices:
                noised[idx] = mask_token_id

    else:
        if use_proportional:
            ratio_normal = len(normal_indices) / len(answer_indices)
            target_normal_keep = int(round(num_to_keep * ratio_normal))
            target_pad_keep = num_to_keep - target_normal_keep

            target_normal_mask = len(normal_indices) - target_normal_keep
            target_pad_mask = len(pad_indices) - target_pad_keep

            def mask_tokens(pool, mask_count):
                if mask_count <= 0 or not pool: return
                if confidence_guided and confidences is not None:
                    pool_confs = [confidences[i] for i in pool]
                    lowest_idx = np.argsort(pool_confs)[:mask_count]
                    for idx in lowest_idx:
                        noised[pool[idx]] = mask_token_id
                else:
                    to_mask = np.random.choice(pool, size=mask_count, replace=False)
                    for idx in to_mask:
                        noised[idx] = mask_token_id

            mask_tokens(normal_indices, target_normal_mask)
            mask_tokens(pad_indices, target_pad_mask)

        else:
            if confidence_guided and confidences is not None:
                answer_confs = [confidences[i] for i in answer_indices]
                lowest_conf_idx = np.argsort(answer_confs)[:num_to_mask]
                for idx in lowest_conf_idx:
                    noised[answer_indices[idx]] = mask_token_id
            else:
                to_mask = np.random.choice(answer_indices, size=num_to_mask, replace=False)
                for idx in to_mask:
                    noised[idx] = mask_token_id

    return noised

def render_tokens(tokens, answer_start, confidences, tokenizer, step, total_steps, frozen_indices=None):
    mask_token_id = tokenizer.encode('MASK', add_special_tokens=False)[0]
    eos_id = tokenizer.eos_token_id

    answer_tokens = tokens[answer_start:]

    try:
        num_tokens = answer_tokens.index(eos_id)
    except ValueError:
        num_tokens = len(answer_tokens)

    html_parts = []
    for i, (tok, conf) in enumerate(zip(answer_tokens, confidences)):
        if tok == eos_id:
            break

        tok_str = tokenizer.decode([tok]).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\n","↵ ")
        global_idx = answer_start + i

        if tok == mask_token_id:
            style = "background:#ccc;border-radius:3px;padding:1px 3px;color:#333"
            tok_str = "MASK"
        elif frozen_indices is not None and global_idx in frozen_indices:
            # Highlight permanently unmasked tokens in blue
            style = "color:#1a73e8;font-weight:700"
        else:
            hue = int(conf * 120)
            style = f"color:hsl({hue},90%,30%);font-weight:{'600' if conf>0.8 else '400'}"

        html_parts.append(f"<span style='{style}' title='conf:{conf:.2f}'>{tok_str}</span>")

    progress_pct = int(100 * step / total_steps)

    return f"""
    <div style="font-family:'Google Sans',Arial,sans-serif;padding:16px;
                border:1px solid #e0e0e0;border-radius:10px;background:#fafafa">
      <div style="font-size:13px;font-weight:700;color:#1a73e8;margin-bottom:6px">
        🔄 Step {step}/{total_steps} ({num_tokens} tokens)
      </div>
      <div style="background:#eee;border-radius:4px;height:8px;margin-bottom:10px">
        <div style="background:#1a73e8;width:{progress_pct}%;height:8px;border-radius:4px"></div>
      </div>
      <div style="line-height:2;font-size:14px;white-space:pre-wrap">{"".join(html_parts)}</div>
    </div>"""

# ── Main inference loop ───────────────────────────────────────────────────────
mask_token_id = tokenizer.encode('MASK', add_special_tokens=False)[0]
eos_token_id = tokenizer.eos_token_id
model.eval()
device = next(model.parameters()).device

prompt_ids   = tokenizer.encode(format_prompt(QUESTION), add_special_tokens=False)
answer_start = find_answer_start(prompt_ids)

# UPDATED: Add MAX_TOKENS directly to the prompt instead of using it as a total length limit
input_ids    = prompt_ids + [mask_token_id] * MAX_TOKENS

out = widgets.Output()
display(out)

frozen_indices = set()
previous_repetitions = set()

with torch.no_grad():
    for step in range(NUM_STEPS + 1):

        input_tensor = torch.tensor([input_ids], dtype=torch.long).to(device)
        logits = model(input_ids=input_tensor)["logits"]

        probs = F.softmax(logits / TEMPERATURE, dim=-1).clamp(min=1e-8)

        probs, topk_idx, topk_vals = top_k_filter(probs, TOP_K)

        # ✅ N-GRAM grammar correction
        if USE_NGRAM_GRAMMAR:
            probs = apply_ngram_grammar_filter(probs.squeeze(0), input_ids, N_GRAM_N).unsqueeze(0)

        generated = torch.multinomial(probs.squeeze(0), num_samples=1).squeeze(-1).tolist()

        confidences = probs.squeeze(0)[range(len(generated)), generated].cpu().numpy()

        if PERMANENT_UNMASK:
            for idx in frozen_indices:
                generated[idx] = input_ids[idx]

        input_ids = input_ids[:answer_start] + generated[answer_start:]

        # ✅ Break stuck repetitions
        current_repetitions = set()
        if REMOVE_STUCK_REPETITIONS:
            i = answer_start
            while i < len(input_ids) - 1:
                tok1 = input_ids[i]
                tok2 = input_ids[i+1]

                if tok1 == tok2 and tok1 not in (mask_token_id, eos_token_id):
                    rep_key = (i, tok1)
                    current_repetitions.add(rep_key)

                    if rep_key in previous_repetitions:
                        conf1 = confidences[i]
                        conf2 = confidences[i+1]

                        if conf1 < 0.7 or conf2 < 0.7:
                            # Remove the duplicate and append an eos at the end to keep length static
                            input_ids.pop(i+1)
                            input_ids.append(eos_token_id)

                            # Keep confidences array in sync
                            confidences = np.delete(confidences, i+1)
                            confidences = np.append(confidences, 1.0)

                            # Shift the frozen indices left if applicable
                            if PERMANENT_UNMASK and frozen_indices is not None:
                                new_frozen = set()
                                for f_idx in frozen_indices:
                                    if f_idx < i + 1:
                                        new_frozen.add(f_idx)
                                    elif f_idx > i + 1:
                                        new_frozen.add(f_idx - 1)
                                frozen_indices = new_frozen

                            # Remove from current repetitions so we don't trip it again instantly
                            current_repetitions.remove(rep_key)

                            # Break out to safely fix just one issue per step (avoids cascading index math bugs)
                            break
                i += 1

        previous_repetitions = current_repetitions

        # Pass frozen_indices to render_tokens only if PERMANENT_UNMASK is enabled
        html = render_tokens(
            input_ids,
            answer_start,
            confidences[answer_start:],
            tokenizer,
            step,
            NUM_STEPS,
            frozen_indices=(frozen_indices if PERMANENT_UNMASK else None)
        )

        with out:
            clear_output(wait=True)
            display(HTML(html))

        if step < NUM_STEPS:
            noise_frac = noising_schedule(step, NUM_STEPS, NOISE_LEVEL)
            input_ids  = renoise(
                input_ids,
                answer_start,
                mask_token_id,
                noise_frac,
                confidences=confidences,
                frozen_indices=frozen_indices,
                permanent_unmask=PERMANENT_UNMASK,
                confidence_guided=CONFIDENCE_GUIDED,
                proportional_unmask=PROPORTIONAL_UNMASK,
                eos_id=eos_token_id
            )

# Final decode
final_tokens = input_ids[answer_start:]
try:
    final_tokens = final_tokens[:final_tokens.index(tokenizer.eos_token_id)]
except ValueError:
    pass

final_text = tokenizer.decode(final_tokens, skip_special_tokens=True)

with out:
    clear_output(wait=True)
    display(HTML(f"""
    <div style="font-family:'Google Sans',Arial,sans-serif;padding:16px;
                border:2px solid #34a853;border-radius:10px;background:#f0fff4">
      <div style="font-weight:700;color:#2e7d32;font-size:15px;margin-bottom:10px">
        ✅ Final Answer (after {NUM_STEPS} steps — {len(final_tokens)} tokens)
      </div>
      <div style="line-height:1.9;font-size:14px;white-space:pre-wrap;color:#202124">
        {final_text}
      </div>
    </div>"""))

#@title 💬 Interactive Denoising Inference { display-mode: "form" }
import torch
import torch.nn.functional as F
import numpy as np
import re
from collections import defaultdict
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets

# ── Config ────────────────────────────────────────────────────────────────────
QUESTION          = "What do you know about Amsterdam?"  #@param {type:"string"}
NUM_STEPS         = 64    #@param {type:"slider", min:1, max:256, step:1}
NOISE_LEVEL       = 0.5   #@param {type:"slider", min:0.0, max:1.0, step:0.05}
TEMPERATURE       = 0.5   #@param {type:"slider", min:0.1, max:2.0, step:0.1}
TOP_K             = 5    #@param {type:"slider", min:1, max:100, step:1}
PERMANENT_UNMASK  = False  #@param {type:"boolean"}
CONFIDENCE_GUIDED = False  #@param {type:"boolean"}
PROPORTIONAL_UNMASK= True  #@param {type:"boolean"}
MAX_TOKENS         = 128   #@param {type:"slider", min:1, max:512, step:1}

USE_NGRAM_GRAMMAR = False  #@param {type:"boolean"}
GRAMMAR_WEIGHT         = 0.95   #@param {type:"slider", min:0.0, max:2.0, step:0.05}

# ── Simple Bigram Table (lazy + cached) ───────────────────────────────────────
bigram_cache = defaultdict(lambda: defaultdict(float))

def get_bigram_score(prev_token, curr_token):
    # Very cheap heuristic instead of full LM:
    # reward space-consistent / punctuation-consistent transitions
    prev = tokenizer.decode([prev_token])
    curr = tokenizer.decode([curr_token])

    score = 0.0

    # simple heuristics (fast)
    if prev.endswith(" ") and curr.startswith(" "):
        score -= 0.5
    if prev.endswith((".", "!", "?")):
        if not curr.strip().startswith((" ", "\n")):
            score -= 0.3
    if prev.strip() == "" and curr.strip() == "":
        score -= 0.5

    # encourage letter continuity
    if prev and curr and prev[-1].isalpha() and curr[0].isalpha():
        score += 0.1

    return score

# ── Helpers ───────────────────────────────────────────────────────────────────
def format_prompt(question):
    return (
        "<|begin_of_text|>\n"
        "<|start_header_id|>system<|end_header_id|>\n"
        "You are a helpful assistant.\n"
        "<|eot_id|>\n"
        "<|start_header_id|>user<|end_header_id|>\n"
        f"{question}\n"
        "<|eot_id|>\n"
        "<|start_header_id|>assistant<|end_header_id|>\n"
    )

def find_answer_start(input_ids):
    marker = tokenizer.encode(
        "<|start_header_id|>assistant<|end_header_id|>\n",
        add_special_tokens=False
    )
    for i in range(len(input_ids) - len(marker) + 1):
        if input_ids[i:i+len(marker)] == marker:
            return i + len(marker)
    return None

def top_k_filter(probs, k):
    topk_vals, topk_idx = torch.topk(probs, k)
    mask = torch.zeros_like(probs).scatter_(-1, topk_idx, 1.0)
    filtered = probs * mask
    filtered = filtered / filtered.sum(dim=-1, keepdim=True)
    return filtered, topk_idx, topk_vals

# ── N-GRAM SCORING ────────────────────────────────────────────────────────────
def ngram_score(sequence, pos, candidate, n):
    """
    Score candidate token at position pos using n-gram context.
    Uses left context only (fast + causal approximation).
    """
    if pos < n - 1:
        return 0.0  # not enough context

    context = sequence[pos - (n - 1):pos]
    ngram = tuple(context + [candidate])
    return ngram_table.get(ngram, -8.0)


def apply_ngram_grammar_filter(probs, input_ids, n):
    """
    Reweight probabilities using n-gram grammar scores.
    Only applied to TOP-K tokens (already filtered).
    """
    probs_np = probs.cpu().numpy()
    new_probs = np.zeros_like(probs_np)

    for i in range(len(input_ids)):
        token_probs = probs_np[i]
        candidates = np.where(token_probs > 0)[0]

        scores = []
        for tok in candidates:
            score = ngram_score(input_ids, i, tok, n)
            scores.append(score)

        scores = np.array(scores)
        scores = np.exp(scores)  # back to prob space

        weighted = token_probs[candidates] * scores
        if weighted.sum() > 0:
            weighted /= weighted.sum()

        new_probs[i, candidates] = weighted

    return torch.tensor(new_probs, device=probs.device)

def grammar_aware_sample(probs, topk_idx, topk_vals, input_ids, answer_start):
    seq_len = probs.shape[0]
    generated = []

    for i in range(seq_len):
        if i < answer_start:
            generated.append(input_ids[i])
            continue

        candidates = topk_idx[i]
        candidate_probs = topk_vals[i]

        best_token = None
        best_score = -1e9

        for tok, p in zip(candidates, candidate_probs):
            tok = tok.item()
            p = p.item()

            score = np.log(p + 1e-8)

            if GRAMMAR_AWARE_DECODING and len(generated) > 0:
                prev_tok = generated[-1]
                score += GRAMMAR_WEIGHT * get_bigram_score(prev_tok, tok)

            if score > best_score:
                best_score = score
                best_token = tok

        generated.append(best_token)

    return generated

def noising_schedule(step, total_steps, noise_level):
    frac = 1.0 - (step / total_steps)
    return noise_level * frac

def renoise(tokens, answer_start, mask_token_id, noise_frac, confidences=None, frozen_indices=None, permanent_unmask=True, confidence_guided=True, proportional_unmask=True, eos_id=None):
    noised = tokens.copy()
    answer_indices = list(range(answer_start, len(tokens)))

    num_to_mask = max(1, int(noise_frac * len(answer_indices)))
    num_to_keep = len(answer_indices) - num_to_mask

    # Find the boundary for proportional splitting
    end_of_answer_idx = len(tokens)
    if eos_id is not None and eos_id in tokens[answer_start:]:
        end_of_answer_idx = answer_start + tokens[answer_start:].index(eos_id)

    normal_indices = [i for i in answer_indices if i < end_of_answer_idx]
    pad_indices = [i for i in answer_indices if i >= end_of_answer_idx]
    use_proportional = proportional_unmask and len(normal_indices) > 0 and len(pad_indices) > 0

    if permanent_unmask and frozen_indices is not None:
        shortfall = num_to_keep - len(frozen_indices)

        if shortfall > 0:
            if use_proportional:
                # Calculate how many normal vs pad tokens SHOULD be frozen in total
                ratio_normal = len(normal_indices) / len(answer_indices)
                target_normal_frozen = int(round(num_to_keep * ratio_normal))
                target_pad_frozen = num_to_keep - target_normal_frozen

                current_normal_frozen = len([i for i in frozen_indices if i < end_of_answer_idx])
                current_pad_frozen = len([i for i in frozen_indices if i >= end_of_answer_idx])

                shortfall_normal = max(0, target_normal_frozen - current_normal_frozen)
                shortfall_pad = max(0, target_pad_frozen - current_pad_frozen)

                unfrozen_normal = [i for i in normal_indices if i not in frozen_indices]
                unfrozen_pad = [i for i in pad_indices if i not in frozen_indices]

                shortfall_normal = min(shortfall_normal, len(unfrozen_normal))
                shortfall_pad = min(shortfall_pad, len(unfrozen_pad))

                # Correct for rounding errors if one bucket maxed out
                remaining = shortfall - (shortfall_normal + shortfall_pad)
                if remaining > 0:
                    if shortfall_normal < len(unfrozen_normal):
                        shortfall_normal += remaining
                    elif shortfall_pad < len(unfrozen_pad):
                        shortfall_pad += remaining

                def freeze_tokens(unfrozen_pool, count):
                    if count <= 0 or not unfrozen_pool: return
                    if confidence_guided and confidences is not None:
                        pool_confs = [confidences[i] for i in unfrozen_pool]
                        best_idx = np.argsort(pool_confs)[-count:]
                        for idx in best_idx:
                            frozen_indices.add(unfrozen_pool[idx])
                    else:
                        rand_idx = np.random.choice(len(unfrozen_pool), size=count, replace=False)
                        for idx in rand_idx:
                            frozen_indices.add(unfrozen_pool[idx])

                freeze_tokens(unfrozen_normal, shortfall_normal)
                freeze_tokens(unfrozen_pad, shortfall_pad)

            else:
                unfrozen_indices = [i for i in answer_indices if i not in frozen_indices]
                shortfall = min(shortfall, len(unfrozen_indices))

                if shortfall > 0 and unfrozen_indices:
                    if confidence_guided and confidences is not None:
                        unfrozen_confs = [confidences[i] for i in unfrozen_indices]
                        best_local_idx = np.argsort(unfrozen_confs)[-shortfall:]
                        for idx in best_local_idx:
                            frozen_indices.add(unfrozen_indices[idx])
                    else:
                        random_local_idx = np.random.choice(len(unfrozen_indices), size=shortfall, replace=False)
                        for idx in random_local_idx:
                            frozen_indices.add(unfrozen_indices[idx])

        # Mask everything not frozen
        for idx in answer_indices:
            if idx not in frozen_indices:
                noised[idx] = mask_token_id

    else:
        if use_proportional:
            ratio_normal = len(normal_indices) / len(answer_indices)
            target_normal_keep = int(round(num_to_keep * ratio_normal))
            target_pad_keep = num_to_keep - target_normal_keep

            target_normal_mask = len(normal_indices) - target_normal_keep
            target_pad_mask = len(pad_indices) - target_pad_keep

            def mask_tokens(pool, mask_count):
                if mask_count <= 0 or not pool: return
                if confidence_guided and confidences is not None:
                    pool_confs = [confidences[i] for i in pool]
                    lowest_idx = np.argsort(pool_confs)[:mask_count]
                    for idx in lowest_idx:
                        noised[pool[idx]] = mask_token_id
                else:
                    to_mask = np.random.choice(pool, size=mask_count, replace=False)
                    for idx in to_mask:
                        noised[idx] = mask_token_id

            mask_tokens(normal_indices, target_normal_mask)
            mask_tokens(pad_indices, target_pad_mask)

        else:
            if confidence_guided and confidences is not None:
                answer_confs = [confidences[i] for i in answer_indices]
                lowest_conf_idx = np.argsort(answer_confs)[:num_to_mask]
                for idx in lowest_conf_idx:
                    noised[answer_indices[idx]] = mask_token_id
            else:
                to_mask = np.random.choice(answer_indices, size=num_to_mask, replace=False)
                for idx in to_mask:
                    noised[idx] = mask_token_id

    return noised

def render_tokens(tokens, answer_start, confidences, tokenizer, step, total_steps, frozen_indices=None):
    mask_token_id = tokenizer.encode('MASK', add_special_tokens=False)[0]
    eos_id = tokenizer.eos_token_id

    answer_tokens = tokens[answer_start:]

    try:
        num_tokens = answer_tokens.index(eos_id)
    except ValueError:
        num_tokens = len(answer_tokens)

    html_parts = []
    for i, (tok, conf) in enumerate(zip(answer_tokens, confidences)):
        if tok == eos_id:
            break

        tok_str = tokenizer.decode([tok]).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\n","↵ ")
        global_idx = answer_start + i

        if tok == mask_token_id:
            style = "background:#ccc;border-radius:3px;padding:1px 3px;color:#333"
            tok_str = "MASK"
        elif frozen_indices is not None and global_idx in frozen_indices:
            # Highlight permanently unmasked tokens in blue
            style = "color:#1a73e8;font-weight:700"
        else:
            hue = int(conf * 120)
            style = f"color:hsl({hue},90%,30%);font-weight:{'600' if conf>0.8 else '400'}"

        html_parts.append(f"<span style='{style}' title='conf:{conf:.2f}'>{tok_str}</span>")

    progress_pct = int(100 * step / total_steps)

    return f"""
    <div style="font-family:'Google Sans',Arial,sans-serif;padding:16px;
                border:1px solid #e0e0e0;border-radius:10px;background:#fafafa">
      <div style="font-size:13px;font-weight:700;color:#1a73e8;margin-bottom:6px">
        🔄 Step {step}/{total_steps} ({num_tokens} tokens)
      </div>
      <div style="background:#eee;border-radius:4px;height:8px;margin-bottom:10px">
        <div style="background:#1a73e8;width:{progress_pct}%;height:8px;border-radius:4px"></div>
      </div>
      <div style="line-height:2;font-size:14px;white-space:pre-wrap">{"".join(html_parts)}</div>
    </div>"""

# ── Main inference loop ───────────────────────────────────────────────────────
mask_token_id = tokenizer.encode('MASK', add_special_tokens=False)[0]
eos_token_id = tokenizer.eos_token_id
model.eval()
device = next(model.parameters()).device

prompt_ids   = tokenizer.encode(format_prompt(QUESTION), add_special_tokens=False)
answer_start = find_answer_start(prompt_ids)

# UPDATED: Add MAX_TOKENS directly to the prompt instead of using it as a total length limit
input_ids    = prompt_ids + [mask_token_id] * MAX_TOKENS

out = widgets.Output()
display(out)

frozen_indices = set()

with torch.no_grad():
    for step in range(NUM_STEPS + 1):

        input_tensor = torch.tensor([input_ids], dtype=torch.long).to(device)
        logits = model(input_ids=input_tensor)["logits"]

        probs = F.softmax(logits / TEMPERATURE, dim=-1).clamp(min=1e-8)

        probs, topk_idx, topk_vals = top_k_filter(probs, TOP_K)


        # ✅ N-GRAM grammar correction
        if USE_NGRAM_GRAMMAR:
            probs = apply_ngram_grammar_filter(probs.squeeze(0), input_ids, N_GRAM_N).unsqueeze(0)

        generated = torch.multinomial(probs.squeeze(0), num_samples=1).squeeze(-1).tolist()

        confidences = probs.squeeze(0)[range(len(generated)), generated].cpu().numpy()

        if PERMANENT_UNMASK:
            for idx in frozen_indices:
                generated[idx] = input_ids[idx]

        input_ids = input_ids[:answer_start] + generated[answer_start:]

        # Pass frozen_indices to render_tokens only if PERMANENT_UNMASK is enabled
        html = render_tokens(
            input_ids,
            answer_start,
            confidences[answer_start:],
            tokenizer,
            step,
            NUM_STEPS,
            frozen_indices=(frozen_indices if PERMANENT_UNMASK else None)
        )

        with out:
            clear_output(wait=True)
            display(HTML(html))

        if step < NUM_STEPS:
            noise_frac = noising_schedule(step, NUM_STEPS, NOISE_LEVEL)
            input_ids  = renoise(
                input_ids,
                answer_start,
                mask_token_id,
                noise_frac,
                confidences=confidences,
                frozen_indices=frozen_indices,
                permanent_unmask=PERMANENT_UNMASK,
                confidence_guided=CONFIDENCE_GUIDED,
                proportional_unmask=PROPORTIONAL_UNMASK,
                eos_id=eos_token_id
            )

# Final decode
final_tokens = input_ids[answer_start:]
try:
    final_tokens = final_tokens[:final_tokens.index(tokenizer.eos_token_id)]
except ValueError:
    pass

final_text = tokenizer.decode(final_tokens, skip_special_tokens=True)

with out:
    clear_output(wait=True)
    display(HTML(f"""
    <div style="font-family:'Google Sans',Arial,sans-serif;padding:16px;
                border:2px solid #34a853;border-radius:10px;background:#f0fff4">
      <div style="font-weight:700;color:#2e7d32;font-size:15px;margin-bottom:10px">
        ✅ Final Answer (after {NUM_STEPS} steps — {len(final_tokens)} tokens)
      </div>
      <div style="line-height:1.9;font-size:14px;white-space:pre-wrap;color:#202124">
        {final_text}
      </div>
    </div>"""))

import torch
import torch.nn.functional as F
import numpy as np


def check_bidirectional_attention(model, tokenizer, dataset, temperature=0.3, num_runs=3):
    model.eval()
    device = next(model.parameters()).device

    # get MASK token id (you said it's literally "MASK")
    mask_token_id = tokenizer("MASK", add_special_tokens=False)["input_ids"][0]

    results = []

    for run in range(num_runs):
        idx = int(np.random.randint(0, len(dataset)))
        sample = dataset[idx]

        assistant_marker = tokenizer.encode(
            "<|start_header_id|>assistant<|end_header_id|>",
            add_special_tokens=False
        )
        input_ids = sample['labels']

        # --- find assistant start ---
        start = None
        for i in range(len(input_ids) - len(assistant_marker)):
            if input_ids[i:i+len(assistant_marker)] == assistant_marker:
                start = i + len(assistant_marker)
                print(start)
                break

        split = start + 5

        input_ids = torch.tensor(input_ids, dtype=torch.long).to(device)
        seq_len = input_ids.shape[0]

        corrupted = input_ids.clone()
        corrupted[start:split] = mask_token_id
        corrupted = corrupted.unsqueeze(0)

        with torch.no_grad():
            logits = model(input_ids=corrupted)["logits"]

        probs = F.softmax(logits / temperature, dim=-1)
        preds = torch.argmax(probs, dim=-1).squeeze(0)

        original = input_ids
        reconstructed = preds

        acc = (reconstructed[:split] == original[:split]).float().mean().item()
        results.append(acc)

        # decode for inspection
        orig_text = tokenizer.decode(original[start:start+20].tolist(), skip_special_tokens=False)
        corrupt_text = tokenizer.decode(corrupted.squeeze(0)[start:start+20].tolist(), skip_special_tokens=False)
        pred_text = tokenizer.decode(reconstructed[start:start+20].tolist(), skip_special_tokens=False)

        print("\n" + "="*80)
        print(f"🔬 Run {run+1}")
        print(f"Reconstruction accuracy (first half): {acc:.3f}")

        if acc > 0.5:
            print("✅ Likely bidirectional (uses future context)")
        elif acc > 0.2:
            print("⚠️ Partial signal")
        else:
            print("❌ Likely causal")

        print("-"*80)
        print("📥 Corrupted input:\n", corrupt_text)
        print("\n🤖 Prediction:\n", pred_text)
        print("\n✅ Original:\n", orig_text)
        print("="*80)

    print("\n📊 Average accuracy:", np.mean(results))

check_bidirectional_attention(
    model=model,
    tokenizer=tokenizer,
    dataset=val_dataset,
    num_runs=3
)

from google.colab import drive
drive.mount('/content/drive')

torch.save(model.state_dict(), "/content/drive/MyDrive/model_8B_LAD.pth")

from google.colab import files
files.download("/content/drive/MyDrive/model_MDLM.pth")

